### ISSUE TITLE
Add Fastlane

### ISSUE THREAD

**Issue by cajeiri** [Webierta/precio-luz#1]
Hello,

Please add a fastlane yml with a description and screenshots. Remember to release a new tag once you do :)

**Comment by Webierta** [comment]
> Hello,
> 
> Please add a fastlane yml with a description and screenshots. Remember to release a new tag once you do :)

Thanks, but I'm a little lost.
There is already the directory 'fastlane / metadata / android' with the description and with screenshots.

**Comment by cajeiri** [comment]
Oh, my bad, 1.1 isn't in F-Droid yet which is why there isn't a description

**Comment by Webierta** [comment]
Anyway, thanks to your comment I have seen that there was an error in versionCode.
Fixed, I hope they upload it to FDroid soon
