### ISSUE TITLE
Propuesta de patrocinio

### ISSUE THREAD

**Issue by Pablohn26** [Webierta/precio-luz#14]
Hola buenas,

me gustaría contactar con el desarrollador del proyecto para hablar sobre una propuesta de patrocinio. He intentado sin éxito buscar un email de contacto. ¿Podrías contactar conmigo por cualquiera de los métodos que aparecen [aquí](https://www.biodrop.io/Pablohn26)?

Saludos y gracias por la aplicación

**Comment by Webierta** [comment]
Hola Pablo, soy el desarrollador de esta aplicación, me pondré en contacto contigo vía Telegram...

**Comment by Pablohn26** [comment]
Muchas gracias

**Comment by Webierta** [comment]
Perdona Pablo, ahora no me funciona Telegram ¿? Puedes contactar conmigo en webiertaARROBAgmail.com
