### ISSUE TITLE
Nueva tarifa 2.0 TD

### ISSUE THREAD

**Issue by alSeveR** [Webierta/precio-luz#2]
La aplicación ya no funciona con la nueva tarifa 2.0 TD que ha entrado en vigor. Estaría genial adaptarla para poder seguir usando una herramienta tan útil y que con esta nueva tarifa lo sería aún más.

Gracias.

**Comment by Webierta** [comment]
Sí, he solicitado que temporalmente la retiren de F-Droid.

Ya me he puesto en marcha para actualizarla a la nueva tarifa, espero poder publicarla pronto.

Un saludo.

**Comment by Webierta** [comment]
Acabo de enviar nueva versión 2.0.0 adaptada a la nueva tarifa, y espero que pronto la publiquen en F-Droid.
Cierro este tema.

**Comment by Webierta** [comment]
Publicada en F-Droid nueva versión adaptada a la actual tarifa.
