### ISSUE TITLE
No se verifica el Token

### ISSUE THREAD

**Issue by aeri** [Webierta/precio-luz#3]
Parece ser que no están comprobando el token de acceso puesto que se acepta cualquier cosa que se inserte en el campo Token. Igual han eliminado ese requisito y ya no es necesario solicitarlo.

**Comment by Webierta** [comment]
Hola, lo sé, pero lo que no sé es cuánto tiempo durará. Por eso en la última versión hice que el método que no usa token hace un primer intento con token (que tiene que estar guardado en un primer intento con token aunque sea falso), y solo si no funciona ejecuta el método segundo que no usa token.
Mientras dure espero que muchos puedan usar la app aunque no tengan token.
Un saludo.
EDITO: no me acordaba, no hace falta que haya un token guardado, siempre hace primero el intento con token.

**Comment by aeri** [comment]
Estupendo, muy buena idea lo del token. Por lo que veo no estamos seguros de si es algo temporal o ya han desactivado la autenticación para esa llamada en concreto de forma permanente. Habrá que estar alerta.
Saludos.
