### ISSUE TITLE
Error en vista por horas

### ISSUE THREAD

**Issue by alSeveR** [Webierta/precio-luz#4]
Como se puede ver en la imagen, en las filas 4 y 5 aparece la hora "1h - 2h". Es posible a que se deba a que tienen el mismo precio...

![photo_2021-07-01_00-07-53](https://user-images.githubusercontent.com/5750163/124037867-84ee5880-da00-11eb-9df3-5d1468478212.jpg)

**Comment by Webierta** [comment]
Gracias por notificar este error. Me pongo a ello para solucionarlo cuanto antes.

**Comment by Webierta** [comment]
He lanzado nueva versión (2.0.4) que creo que soluciona este error (supongo que en unos días la actualizarán en F-Droid, y también dejo aquí archivo apk).
No he podido probar la solución tanto como me hubiera gustado porque los datos de la nueva tarifa solo están disponibles desde el 1 de junio, y desde entonces solo en 2 días se han repetido precios.
Por eso agradezco cualquier observación de posibles errores inesperados que me pueda ayudar a mejorar esta App para todos.

**Comment by Webierta** [comment]
La versión 2.0.4 mantiene un error cuando existen precios repetidos en distintas horas del día. La versión 2.0.5 soluciona definitivamente este error.
