### ISSUE TITLE
[Sugerencia] Franja más barata

### ISSUE THREAD

**Issue by alSeveR** [Webierta/precio-luz#5]
Creo que sería útil una opción con la que poder saber en qué horario sería más barato un determinado número de horas consecutivas.
Ejemplo: El ciclo de mi lavavajillas es de 3 horas. Para saber qué horario es el más barato no me basta con saber la hora más barata, ya que necesitaría saber las 3 horas consecutivas más baratas (ir sumando grupos y haciendo medias).

**Comment by Webierta** [comment]
Lo tendré en cuenta para futuras versiones. Gracias por la sugerencia,

**Comment by Webierta** [comment]
Acabo de lanzar la versión 2.1.0 (aunque todavía no han publicado la versión previa, la 2.0.5).

Además de otras pequeñas mejoras, esta última actualización incluye una herramienta para calcular las franjas horarias consecutivas más baratas (en tramos de media hora). La he probado todo lo que he podido y no he encontrado errores, pero me gustaría conocer más experiencias. Por eso, como siempre, estoy abierto a sugerencias y notificaciones de posibles errores.

Si no aparecen errores, daré por cerrado este asunto.

**Comment by alSeveR** [comment]
La acabo de probar (de forma no exahustiva) y me ha parecido genial. A primera vista no he encontrado ningún error. Muchas gracias.

**Comment by Webierta** [comment]
Bien, como siempre, estoy abierto a más sugerencias de nuevas funciones.
Por cierto, en F-Droid acaban de lanzar la versión 2.0.5, así que espero que ésta esté pronto disponible.

**Comment by Webierta** [comment]
Con la nueva versión (2.1.1) que entre otras mejoras admite cualquier intervalo de tiempo (sin redondear), doy por solucionado este asunto.
