### ISSUE TITLE
Abanico de precios del archivo

### ISSUE THREAD

**Issue by juanalbglz** [Webierta/precio-luz#6]
Hola, creo que el abanico de precios del archivo no refleja los precios del día archivado sino del día en curso, dudo que la gráfica también sea del histórico, aunque no tengo como comprobarlo
![Screenshot_2022-02-23-09-12-48-910_com.pvpc.precio_luz.jpg](https://user-images.githubusercontent.com/2136913/155290989-c8f72cf3-5236-4946-b6bd-1318f9813917.jpg)![Screenshot_2022-02-23-09-11-55-187_com.pvpc.precio_luz.jpg](https://user-images.githubusercontent.com/2136913/155291000-aadc4342-6ef1-4664-949f-d84c38174911.jpg)![Screenshot_2022-02-23-09-10-48-603_com.pvpc.precio_luz.jpg](https://user-images.githubusercontent.com/2136913/155291056-83d799b4-4157-4424-88a5-96ff37c7cce8.jpg)

**Comment by Webierta** [comment]
Hola, gracias por tu comentario. En las imágenes que adjuntas, veo que utilizas una versión anterior. Recomiendo actualizar a la última versión (2.4.1) donde se corrigen una serie de errores y se añaden mejoras.
Un saludo.
EDITO: En las versiones previas la gráfica inicial siempre señalaba los datos del día actual, pero no se trata de un error en el tratamiento de datos, aunque puede llevar al error de pensar que fuera así. Por eso se cambió en la última versión para no inducir a error. Gracias por tu interés.

**Comment by juanalbglz** [comment]
Disculpa que no haya respondido. ¿Sería mucho lío publicar esa última versión en F-Droid? Así sería accesible para muchas más personas. La que está en F-Droid es de la que mandé la captura de pantalla.

**Comment by Webierta** [comment]
Hola, en F-Droid está publicada la última versión (2.4.1) desde el día 16 de noviembre de 2021. Posiblemente necesites actualizar los repositorios, un saludo.
