### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [Webierta/precio-luz#8]
```
* Where:
Build file '/builds/fdroid/fdroiddata/build/com.pvpc.precio_luz/android/app/build.gradle' line: 31
* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'ndkVersion' for extension 'flutter' of type FlutterExtension.
```

I guess we need to update the flutter version? Which flutter should be used? Could you please add the flutter repo as a git submodule so that we don't need to bump the flutter version manully? Please also check the pubspec.lock file into the repo. Thanks!

**Comment by amitamrutiya** [comment]
The Solutions above worked for me. Just to re-echo it here.

Go to the android\app\build.gradle file

android {
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion // line to change

and change ndkVersion to the latest version. It is probably around line 30.

android {
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion "23.1.7779620"

**Comment by Webierta** [comment]
Thanks, I think I've fixed it (I'm in bed with a fever and I'm not sure about it; fever is not my girlfriend's name).

**Comment by linsui** [comment]
Thanks! Hope you feel better soon.
